# Generated by Django 2.0.13 on 2020-02-14 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_auto_20200214_0150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='slug',
            field=models.SlugField(default='', editable=False),
        ),
    ]
